set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_net)
FIND_PATH(small_net_INCLUDE_DIRS small_net.h ${PACKAGE_PATH}/)
FIND_LIBRARY(small_net_LIBRARIES libsmall_net.a PATH ${PACKAGE_PATH}/build)
IF (small_net_INCLUDE_DIRS AND small_net_LIBRARIES)
	SET(small_net_FOUND TRUE)
ENDIF (small_net_INCLUDE_DIRS AND small_net_LIBRARIES)
IF (small_net_FOUND)
    IF (NOT small_net_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_net: ${small_net_LIBRARIES}")
    ENDIF (NOT small_net_FIND_QUIETLY)
ELSE (small_net_FOUND)
    IF (small_net_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_net library")
    ENDIF (small_net_FIND_REQUIRED)
ENDIF (small_net_FOUND)

#depends
find_package(Boost REQUIRED COMPONENTS system)
if (Boost_FOUND)
    SET(small_net_INCLUDE_DIRS ${small_net_INCLUDE_DIRS} ${Boost_INCLUDE_DIRS})
    SET(small_net_LIBRARIES ${small_net_LIBRARIES} ${Boost_LIBRARIES})
endif()

find_package(jsoncpp CONFIG REQUIRED)
SET(small_net_INCLUDE_DIRS ${small_net_INCLUDE_DIRS} ${jsoncpp_INCLUDE_DIRS})
SET(small_net_LIBRARIES ${small_net_LIBRARIES} jsoncpp_lib_static)

find_package(log REQUIRED)
SET(small_net_INCLUDE_DIRS ${small_net_INCLUDE_DIRS} ${log_INCLUDE_DIRS})
SET(small_net_LIBRARIES ${small_net_LIBRARIES} ${log_LIBRARIES})
