set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_timer)
FIND_PATH(small_timer_INCLUDE_DIRS small_timer.h ${PACKAGE_PATH}/)
FIND_LIBRARY(small_timer_LIBRARIES libsmall_timer.a PATH ${PACKAGE_PATH}/build)
IF (small_timer_INCLUDE_DIRS AND small_timer_LIBRARIES)
	SET(small_timer_FOUND TRUE)
ENDIF (small_timer_INCLUDE_DIRS AND small_timer_LIBRARIES)
IF (small_timer_FOUND)
    IF (NOT small_timer_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_timer: ${small_timer_LIBRARIES}")
    ENDIF (NOT small_timer_FIND_QUIETLY)
ELSE (small_timer_FOUND)
    IF (small_timer_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_timer library")
    ENDIF (small_timer_FIND_REQUIRED)
ENDIF (small_timer_FOUND)

find_package(small_net REQUIRED)
SET(small_timer_INCLUDE_DIRS ${small_timer_INCLUDE_DIRS} ${small_net_INCLUDE_DIRS})
SET(small_timer_LIBRARIES ${small_timer_LIBRARIES} ${small_net_LIBRARIES})
