set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_flow)
FIND_PATH(small_flow_INCLUDE_DIRS small_flow.h ${PACKAGE_PATH}/)

IF (small_flow_INCLUDE_DIRS)
	SET(small_flow_FOUND TRUE)
ENDIF (small_flow_INCLUDE_DIRS)
IF (small_flow_FOUND)
    IF (NOT small_flow_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_flow ${small_flow_LIBRARIES}")
    ENDIF (NOT small_flow_FIND_QUIETLY)
ELSE (small_flow_FOUND)
    IF (small_flow_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_flow library")
    ENDIF (small_flow_FIND_REQUIRED)
ENDIF (small_flow_FOUND)

find_package(small_server REQUIRED)
SET(small_flow_INCLUDE_DIRS ${small_flow_INCLUDE_DIRS} ${small_server_INCLUDE_DIRS})
SET(small_flow_LIBRARIES ${small_flow_LIBRARIES} ${small_server_LIBRARIES})
