set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_grpc)
#FIND_PATH(small_grpc_INCLUDE_DIRS small_grpc.h ${PACKAGE_PATH}/)
#FIND_LIBRARY(small_grpc_LIBRARIES libsmall_grpc.a PATH ${PACKAGE_PATH}/build)
set(small_grpc_INCLUDE_DIRS ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_grpc/grpc/include)
set(small_grpc_INCLUDE_DIRS ${small_grpc_INCLUDE_DIRS} ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_grpc/grpc/third_party/protobuf/src)
SET(GRPCC++_LIBRARIES ${PACKAGE_PATH}/build/libgrpc++.a)
SET(GRPC_LIBRARIES ${PACKAGE_PATH}/build/libgrpc.a)
SET(PROTOBUF_LIBRARIES ${PACKAGE_PATH}/build/libprotobuf.a)
SET (small_grpc_LIBRARIES ${GRPCC++_LIBRARIES} 
    ${GRPC_LIBRARIES} ${PROTOBUF_LIBRARIES})

IF (small_grpc_INCLUDE_DIRS AND GRPCC++_LIBRARIES AND GRPC_LIBRARIES AND PROTOBUF_LIBRARIES)
	SET(small_grpc_FOUND TRUE)
ENDIF (small_grpc_INCLUDE_DIRS AND GRPCC++_LIBRARIES AND GRPC_LIBRARIES AND PROTOBUF_LIBRARIES)
IF (small_grpc_FOUND)
    IF (NOT small_grpc_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_grpc: ${small_grpc_LIBRARIES}")
    ENDIF (NOT small_grpc_FIND_QUIETLY)
ELSE (small_grpc_FOUND)
    IF (small_grpc_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_grpc library")
    ENDIF (small_grpc_FIND_REQUIRED)
ENDIF (small_grpc_FOUND)
