set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_http_client)
FIND_PATH(small_http_client_INCLUDE_DIRS small_http_client.h ${PACKAGE_PATH}/)
FIND_LIBRARY(small_http_client_LIBRARIES libsmall_http_client.a PATH ${PACKAGE_PATH}/build)

IF (small_http_client_INCLUDE_DIRS AND small_http_client_LIBRARIES)
	SET(small_http_client_FOUND TRUE)
ENDIF (small_http_client_INCLUDE_DIRS AND small_http_client_LIBRARIES)
IF (small_http_client_FOUND)
    IF (NOT small_http_client_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_http_client: ${small_http_client_LIBRARIES}")
    ENDIF (NOT small_http_client_FIND_QUIETLY)
ELSE (small_http_client_FOUND)
    IF (small_http_client_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_http_client library")
    ENDIF (small_http_client_FIND_REQUIRED)
ENDIF (small_http_client_FOUND)

find_package(small_timer REQUIRED)
SET(small_http_client_INCLUDE_DIRS ${small_http_client_INCLUDE_DIRS} ${small_timer_INCLUDE_DIRS})
SET(small_http_client_LIBRARIES ${small_http_client_LIBRARIES} ${small_timer_LIBRARIES})

find_package(small_packages REQUIRED)
SET(small_http_client_INCLUDE_DIRS ${small_http_client_INCLUDE_DIRS} ${small_packages_INCLUDE_DIRS})
SET(small_http_client_LIBRARIES ${small_http_client_LIBRARIES} ${small_packages_LIBRARIES})
