set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_test)
FIND_PATH(small_test_INCLUDE_DIRS small_test.h ${PACKAGE_PATH}/)
FIND_LIBRARY(GTEST_LIBRARIES libgtest.a PATH ${PACKAGE_PATH}/build)
FIND_LIBRARY(GMOCK_LIBRARIES libgmock.a PATH ${PACKAGE_PATH}/build)
SET (small_test_LIBRARIES ${GTEST_LIBRARIES} ${GMOCK_LIBRARIES})

IF (small_test_INCLUDE_DIRS AND GTEST_LIBRARIES AND GMOCK_LIBRARIES)
	SET(small_test_FOUND TRUE)
ENDIF (small_test_INCLUDE_DIRS AND GTEST_LIBRARIES AND GMOCK_LIBRARIES)
IF (small_test_FOUND)
    IF (NOT small_test_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_test: ${small_test_LIBRARIES}")
    ENDIF (NOT small_test_FIND_QUIETLY)
ELSE (small_test_FOUND)
    IF (small_test_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_test library")
    ENDIF (small_test_FIND_REQUIRED)
ENDIF (small_test_FOUND)
