set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_config)
FIND_PATH(small_config_INCLUDE_DIRS small_config.h ${PACKAGE_PATH}/)
FIND_LIBRARY(small_config_LIBRARIES libsmall_config.a PATH ${PACKAGE_PATH}/build)
IF (small_config_INCLUDE_DIRS AND small_config_LIBRARIES)
	SET(small_config_FOUND TRUE)
ENDIF (small_config_INCLUDE_DIRS AND small_config_LIBRARIES)
IF (small_config_FOUND)
    IF (NOT small_config_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_config: ${small_config_LIBRARIES}")
    ENDIF (NOT small_config_FIND_QUIETLY)
ELSE (small_config_FOUND)
    IF (small_config_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_config library")
    ENDIF (small_config_FIND_REQUIRED)
ENDIF (small_config_FOUND)

#depends
find_package(log REQUIRED)
SET(small_config_INCLUDE_DIRS ${small_config_INCLUDE_DIRS} ${log_INCLUDE_DIRS})
SET(small_config_LIBRARIES ${small_config_LIBRARIES} ${log_LIBRARIES})
