set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_hiredis)
FIND_PATH(small_hiredis_INCLUDE_DIRS small_hiredis.h ${PACKAGE_PATH}/)
FIND_LIBRARY(small_hiredis_LIBRARIES libsmall_hiredis.a PATH ${PACKAGE_PATH}/build)

IF (small_hiredis_INCLUDE_DIRS AND small_hiredis_LIBRARIES)
	SET(small_hiredis_FOUND TRUE)
ENDIF (small_hiredis_INCLUDE_DIRS AND small_hiredis_LIBRARIES)
IF (small_hiredis_FOUND)
    IF (NOT small_hiredis_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_hiredis: ${small_hiredis_LIBRARIES}")
    ENDIF (NOT small_hiredis_FIND_QUIETLY)
ELSE (small_hiredis_FOUND)
    IF (small_hiredis_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_hiredis library")
    ENDIF (small_hiredis_FIND_REQUIRED)
ENDIF (small_hiredis_FOUND)
