set(PACKAGE_PATH ${SHEEP_PROJECT_SOURCE_DIR}/src/extends/small_http_parser)
FIND_PATH(small_http_parser_INCLUDE_DIRS small_http_parser.h ${PACKAGE_PATH}/)
FIND_LIBRARY(small_http_parser_LIBRARIES libsmall_http_parser.a PATH ${PACKAGE_PATH}/build)

IF (small_http_parser_INCLUDE_DIRS AND small_http_parser_LIBRARIES)
	SET(small_http_parser_FOUND TRUE)
ENDIF (small_http_parser_INCLUDE_DIRS AND small_http_parser_LIBRARIES)
IF (small_http_parser_FOUND)
    IF (NOT small_http_parser_FIND_QUIETLY)
        MESSAGE(STATUS "Found small_http_parser: ${small_http_parser_LIBRARIES}")
    ENDIF (NOT small_http_parser_FIND_QUIETLY)
ELSE (small_http_parser_FOUND)
    IF (small_http_parser_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find small_http_parser library")
    ENDIF (small_http_parser_FIND_REQUIRED)
ENDIF (small_http_parser_FOUND)
